#%RAML 1.0
title: The BeerTrader api
description: This is the API for the world famous Beer Trader API
version: v1
baseUri:
  value: http://www.beertrader.com/services/{version}
protocols: [  HTTP, HTTPS ]
mediaType: [ application/json ]
uses:
  ramltopojo: ramltopojo.raml
types:
  BeerType:
    enum: [ALE, STOUT, LAGER, PORTER, MALTS, OTHER]
  BeerStyle:
    enum:
      - AMBER
      - BLOND
      - BROWN
      - CREAM
      - DARK
      - FRUIT
      - GOLDEN
      - HONEY
      - IPA
      - LIGHT
      - LIME
      - PALE
      - PILSNER
      - STRONG
      - RED
      - PILSNER
      - WHEAT
      - OTHER

  UUID:
      (ramltopojo.types):
        plugins:
          - name: core.changeType
            arguments: [ java.util.UUID ]
        type: string
        pattern: "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"

  Identified:
    (ramltopojo.types):
      plugins:
        - core.makeAbstract
    additionalProperties: false
    properties:
      id: UUID

  UserProperties:
    (ramltopojo.types):
      plugins:
        - core.makeAbstract
    additionalProperties: false
    type: Identified
    properties:
      name: string
      email: string
  User:
    (ramltopojo.types):
      plugins:
        - core.jackson
    additionalProperties: true
    type: UserProperties

  BeerProperties:
    (ramltopojo.types):
      plugins:
        - core.makeAbstract
    additionalProperties: false
    type: Identified
    properties:
      name: string
      description: string
      type: BeerType
      style: BeerStyle
  Beer:
    (ramltopojo.types):
      plugins:
        - core.jackson
    additionalProperties: true
    type: BeerProperties

  InventoryEntryProperties:
    (ramltopojo.types):
      plugins:
        - core.makeAbstract
    additionalProperties: false
    type: Identified
    properties:
      count: integer
      availableCount: integer
  InventoryEntry:
    (ramltopojo.types):
      plugins:
        - core.jackson
    type: InventoryEntryProperties
    additionalProperties: true
    properties:
       beerReference: UUID

  TradeProperties:
    (ramltopojo.types):
      plugins:
        - core.makeAbstract
    additionalProperties: false
    type: Identified
    properties:
      fromCount: integer
      toCount: integer
  Trade:
    (ramltopojo.types):
      plugins:
        - core.jackson
    type: TradeProperties
    additionalProperties: true
    properties:
      fromUserReference: UUID
      fromBeerReference: UUID
      toUserReference: UUID
      toBeerReference: UUID

resourceTypes:
  collection:
    get:
      responses:
        200:
          body:
            application/json: <<targetType>>[]
    post:
      body:
        application/json: <<targetType>>
      responses:
        201:
          headers:
            Location: string
          body:
            application/json: <<targetType>>
  item:
    get:
      responses:
        200:
          body:
            application/json: <<itemType>>
        404:
    delete:
      responses:
        200:
        404:
    put:
      body:
        application/json: <<itemType>>
      responses:
        200:
        404:
/users:
  type: { collection: { targetType: User } }
  /{userId}:
    type: { item: { itemType: User } }

/users/{userId}/inventory:
  type: { collection: { targetType: InventoryEntry } }
  /{entryId}:
    type: { item: { itemType: InventoryEntry } }

/users/{userId}/beers:
  type: { collection: { targetType: Beer } }
  /{entryId}:
    type: { item: { itemType: Beer } }

/users/{userId}/trades:
  type: { collection: { targetType: Trade } }
  /{tradeId}:
    type: { item: { itemType: Trade } }
